# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 200

checkpoint:
  save_interval: 200
  save_interval_updates: 200
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: audio_pretraining
  data: ???
  normalize: true
  labels: ltr

dataset:
  num_workers: 6
  max_tokens: 1280000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 0
  validate_interval: 200
  validate_interval_updates: 200
  valid_subset: ???
  train_subset: ???

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 4
  distributed_port: 0

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 10000
  lr: [0.0001]
  sentence_avg: true
  update_freq: [5]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.75
  mask_length: 10
  mask_channel_prob: 0.256
  mask_channel_length: 64
  mask_channel_other: 0
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0

